### ISSUE TITLE
Couldn't replicate the results for VAE-WL using this code/architecture 

### ISSUE THREAD

**Issue by dronaak** [ricardodcpereira/VAE-WL#1]
For the MNIST dataset, I’m getting a mean absolute error value of 0.135 for a missing rate of 40% using this code but in the paper, it shows 0.037 for a missing rate of 40% which is almost 3.5 times better than my result. I have followed all the requirements, setup, and also code matches with the architecture published in the paper but I'm unable to replicate the values published in the paper for VAE-WL for different missing rates.

**Comment by ricardodcpereira** [comment]
I just pushed to the repo a few changes to the code. The implementation was missing some regularization components and a few architectural details. Such changes should help reduce the gap in the results that you are experiencing. Nevertheless, this gap exists because of the TensorFlow versions. The original code used for the paper results was implemented with TF1, while this public version is implemented with TF2. For some unclear reasons, TF2 leads to slightly worse results for all methods considered in the paper.
